version: '3'

services: 
  database:
    image: postgres:latest
    container_name: 'banking-database'
    ports: 
      - '${DB_PORT}:5432' #computer:container
    restart: always
    volumes:
      - ./database-backup:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    
  app:
    build: .
    container_name: banking-api
    ports: 
      - '${PORT}:${PORT}'

volumes:
  database-backup: 
